services:
  userservice:
    build: ./userservice
    ports:
      - "8083:8083"
  
  orderservice:
    build: ./orderservice
    ports:
      - "8082:8082"
    depends_on:
      - productservice

  productservice:
    build: ./productservice
    ports:
      - "8081:8081"

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - userservice
      - orderservice
      - productservice
